---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: openldap
  namespace: networking
spec:
  interval: 15m
  chart:
    spec:
      chart: openldap-stack-ha
      version: 3.0.2
      sourceRef:
        kind: HelmRepository
        name: jp-gouin
        namespace: flux-system
  values:
    global:
      ldapDomain: ${SECRET_DOMAIN}
    replicaCount: 1
    replication:
      enabled: false
    image:
      repository: osixia/openldap
      tag: 1.5.0
      pullPolicy: IfNotPresent
    existingSecret: openldap
    env:
      LDAP_ORGANISATION: ${LDAP_ORGANISATION}
      LDAP_READONLY_USER_USERNAME: ${LDAP_READONLY_USER_USERNAME}
      LDAP_READONLY_USER_PASSWORD: ${LDAP_READONLY_USER_PASSWORD}
    persistence:
      enabled: true
      existingClaim: openldap-pvc
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        memory: 256Mi
    ltb-passwd:
      enabled: true
      image:
        tag: 5.2.3
      ingress:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-staging"
          external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
          external-dns/is-public: "true"
        hosts:
          - host: ssl-ldap2.${SECRET_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - ssl-ldap2.${SECRET_DOMAIN}
            secretName: "ssl-ldap2-tls"
      ldap:
        server: ldaps://openldap-openldap-stack-ha
        existingSecret: openldap
        bindDN: LDAP_BINDDN
        bindPWKey: LDAP_ADMIN_PASSWORD
    phpldapadmin:
      enabled: true
      env:
        PHPLDAPADMIN_LDAP_CLIENT_TLS_REQCERT: "never"
      ingress:
        enabled: true
        ingressClassName: "nginx"
        podAnnotations:
          cert-manager.io/cluster-issuer: "letsencrypt-staging"
          external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
          external-dns/is-public: "true"
        hosts:
          - host: phpldapadmin.${SECRET_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - phpldapadmin.${SECRET_DOMAIN}
            secretName: phpldapadmin-tls
