apiVersion: v1
kind: Secret
metadata:
    name: openldap-secret
    namespace: networking
stringData:
    LDAP_ORGANISATION: ENC[AES256_GCM,data:rlDKUJns9OT4gVmu0YyPJOSJTw==,iv:LiS6tR8i6fmIO/4t2+UeRL3rQK3yE8JatWCKvIUYFxc=,tag:9tdXMEIe/IC3NVqLWOOq/g==,type:str]
    LDAP_BINDDN: ENC[AES256_GCM,data:z0jpeGvnvyKapY+m2jfZB1r0x0zPuek+aahUBg==,iv:fPh1vckt7lW2U2SNX/TY4/mhPh+WcyOcVs7/Q8+68AE=,tag:5DYDqPSx3sRP90kdjuNTrQ==,type:str]
    LDAP_ADMIN_PASSWORD: ENC[AES256_GCM,data:gOFC0auIg7JluU5RnZOVDKKZ4rzFbsnO71ibQ4LrRn/J9cUp3q2l0eBA1ST/1P4BO135UwjBpJYovs8XDI8eGQ==,iv:8npWBzyb0sbVCqAQmRdJshKjimaeHFgAM4pgYwRiweQ=,tag:TN0AykmK4Z5Frax8IVrMHg==,type:str]
    LDAP_CONFIG_PASSWORD: ENC[AES256_GCM,data:/76zrGtkSW/wZua3sqnfwwQtiXDHVlnsnnRidMQUqjYxaxoh3bfdyA+OFfXPjZhaxfpetLnDdm9jXAj1wyxP/w==,iv:oM9Jg10MLpYKL/ekFxIRpalxXfcXLsvZp5RGik+RCZQ=,tag:hRMT/gECFxiM7g8O0Xa59w==,type:str]
    LDAP_READONLY_USER_USERNAME: ENC[AES256_GCM,data:DYqpvqqpQb0=,iv:rb0z0OFIZGU9JonCzKB9J29GfVBLaYPP20gpciHfAKg=,tag:2Cg2h6wf0CmWMytJczzP7Q==,type:str]
    LDAP_READONLY_USER_PASSWORD: ENC[AES256_GCM,data:LF6cTwrAgDGL10jgCr9s9WeT9YOGVKmhIPxf4paP9uJsod1xWnLvcFKYHm9LAJKbGTLPFYQOe+wNeJJ/fA0bOw==,iv:LeCy38qXY9BtQMkyKRUcP2Cp4UxqdYH45L9cbPfM1IU=,tag:p6tweDGWgXdMSvCLQmcvVQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17cmuq9q08fkx2vd0crtmly4vlzwllf6lj83rwsvgg4p9rt0fxa5s0t0xtw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmS2dZYVBYQm9oNHg3WWVp
            WGdLU01BbFgxOWg5VWFHZlhNbWRROE5BOEhnCnkrM0l4enIvNUhtUmJzQVdkOFJo
            TkVRRytZSTFJd2wzZFZ3SHBKNllHeDQKLS0tIGV3b2FNRCtHdW9Cb0F2bWV1YTVX
            SHZTZWExS0hGbi9DcmFhc2dlN3pCYUkKFOKBnRwSewDIKfTsmhtqedIOYT4yRaAv
            nybOjURhkALn9budLf76SmgqL/DFQGnItSrdC3wTXJYvaqBdHvxE6w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-11-20T17:52:58Z"
    mac: ENC[AES256_GCM,data:JzNrY1g6k47hygA0SYy6z1gfHH6gsHRLicGCGK3STLPOdqwMRjBLTwj+coul76IWscnxS1hKPtBbCNlxzCeBrGB90Cy3dT2JpVM1YfLx8mXMKh0FCB+yp41+zNeiJ7gAGprEn7yktrM0E1xsLaJDz5qicQrIKlr91c8uT7CtJO0=,iv:3UW8qdqzqHqq4UbobRc4XcCzmDEzOUgdHj0DKobmP/8=,tag:TPOnCa7Mv+W5gff9JC+Tpw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
