apiVersion: v1
kind: Secret
metadata:
    name: openldap
    namespace: networking
stringData:
    LDAP_ORGANISATION: ENC[AES256_GCM,data:P4DuHyBn2DSHAUfg,iv:WzDIMSGu+an72tPokqA/ga0OsE1KPHkXw0nhfIANa2s=,tag:NcZklFhXHZGWVKJ/eb8Z/A==,type:str]
    LDAP_ADMIN_PASSWORD: ENC[AES256_GCM,data:t7IonnEEm0aEpgm7H/qAvYSTnzfc8L8HitZGq7Q9,iv:CkwjdwXQKAYtsBhVvbStQVP74i+bycw16lMjF/Bfbf4=,tag:ruHIi32CTkjYYZRV0Aj4wA==,type:str]
    LDAP_CONFIG_PASSWORD: ENC[AES256_GCM,data:lPjvHeXxj7vLPk6k06VxSCumgUBguA==,iv:4NCgALsLxwvcmJy6PP4NjV24MxuHSe4S7ptMhzEHj1o=,tag:eiFt/LyA8l0WrkZAJFs83w==,type:str]
    LDAP_READONLY_USER_USERNAME: ENC[AES256_GCM,data:5Qf3g29Kd3M=,iv:1DbpdrsuwTocOQ46Uq2rgC4kIAk0+jYEat6hcP5+KpI=,tag:AJOkZOdWIz4NPjuUn+tM3w==,type:str]
    LDAP_READONLY_USER_PASSWORD: ENC[AES256_GCM,data:HdEvQJHaRIp6Zo9ZCDHQwXape5h7vLdi7wY=,iv:pFAUdHVpTbOL9b/+xHxHmmz3PklKD4WhQdXeogice2E=,tag:nrsPQwgQPdHgSCZs0sobWA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17cmuq9q08fkx2vd0crtmly4vlzwllf6lj83rwsvgg4p9rt0fxa5s0t0xtw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTMFFKOFZUTFg3NzRIa1NR
            dmxMMXdKTzlKLzUzZVV5ZDB6T0l1OUU1MjNRClhKWjFnekZwZWRXWnZjOW9EWVNv
            cmFVWktKb2Y2T0VySkdUZHRJUGdXbWsKLS0tIG5MU2lHcnJIOGpZcTJoc1BzNzdj
            WXNJTW9ib1VTTjVaV0hCd3BsWGZvOEEKblBDSvEQ4+iv71CwIe0tTP78CBzWysWu
            PXbo5662ENsVbqqyJUI6UV5LKZolw2Hf8KpKoSf0wE7jyWRhjlFosQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-11-04T15:14:35Z"
    mac: ENC[AES256_GCM,data:xMZIwNEfGYuRQzjxZoVluzBh4NutS2uP2oNDLB7o3AbOFAkXxGAIJ+GSuWi3Lt2CkC6X3Hl96XaOIJVmoKfn1/A2/2RAWI7Ce4qRsB8oqQM/3xbv+Iar1EJOigWTNpfL4rEbBbiFeueRjB+rRKYgbEToHAXUWZAYfdZ7Lo8w7yk=,iv:+xJd2CIlyAGFa4HpKD9SeKrodX2iWSEMB0wbG3AMSHs=,tag:wVbNc5BVsn1fDFY3wl1e6Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
