# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: openldap
    namespace: networking
stringData:
    SECRET_LDAP_ORGANISATION: ENC[AES256_GCM,data:M0Yef3xYq+361Jzr,iv:D0s8czuAdNzAMEPA5Adug2Yqu9G878gWsd7kZjZ03aU=,tag:kh9W90blCHqZgbBvhjNHMQ==,type:str]
    SECRET_LDAP_DOMAIN: ENC[AES256_GCM,data:sKgyw1wz8JMkE23oSQ==,iv:ZV4oTaExK16OrUbCdNyJp5Toc4JryZF0VpZjfb476iQ=,tag:r5EFRS9oDJ8+e0vbXtjT9w==,type:str]
    SECRET_LDAP_BASE_DN: ENC[AES256_GCM,data:n4Q+NmZiLNNGA+awqA==,iv:Pvsg71EvVsSs9MAzk4fVVwpGXvRYuHmT3KLJFqgGOCA=,tag:z2m4h0Eb090/qtqtnQYFOw==,type:str]
    SECRET_LDAP_ADMIN_PASSWORD: ENC[AES256_GCM,data:cYZKmZq6k/yMvWRkpddnJ51+QIK2h6NLGVE+8GIk,iv:4TiPnMsx83zR+QD07p8a/Tyqxx9ZcGDVs4740HaFgZo=,tag:UIgQ2DAXkR8jyS/EELWKMA==,type:str]
    SECRET_LDAP_CONFIG_PASSWORD: ENC[AES256_GCM,data:WguLUzVyfOiVh1Q1MA3CRnoGag8ASw==,iv:LyvTQxu4KlQkC/ZOgw4mgLwcTZJCdid6HKWobs9vBsI=,tag:farxS0owDhHG9ksiBc7c0g==,type:str]
    SECRET_LDAP_READONLY_USER: ENC[AES256_GCM,data:348uwA==,iv:M3uQTZWcwlyQ0u5oI1UN+bG4WQfgWLwuv5h2lNyDDnA=,tag:1oD0ZDi0ZW10AJArXmDRig==,type:bool]
    SECRET_LDAP_READONLY_USER_USERNAME: ENC[AES256_GCM,data:KNorZn6G9Bw=,iv:ozTFLXZoNH3Zt2Y+UMe54xtejWj99TJMqmHqJsVCkCs=,tag:LDVNNP4mBrRLhYyzZgHVOw==,type:str]
    SECRET_LDAP_READONLY_USER_PASSWORD: ENC[AES256_GCM,data:daifzLpPj7CwviXaIgnr0GTMFwzHkk55ayQ=,iv:1Co06vGhf+l2EzHpEBlHmEGPLiMvIMvQVbCr/HkLbpY=,tag:rDyAcw/VL4GdY4Tgr11/zQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17cmuq9q08fkx2vd0crtmly4vlzwllf6lj83rwsvgg4p9rt0fxa5s0t0xtw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjak44UTRQdERpbUVrZWlJ
            ZWRPcGwvNSs5bzczblBUb0x2MStJVlozaFRZCkhod2pXNVJhSzFadmp6a1NNekdT
            eEpYcUVOT0V4bEFsRFlSMmNBZndYd28KLS0tIFFFQ1c1NWhiYUE5YVBpb2lZYTRY
            ZkN4eFluTVJ3dDRaV3VEcVhmWmErR2MKUN48tZ7GzQBE9ywZg4UNZ/QSRlsn4WZW
            eM6+DCi6k4v1hGT0Pk2pjIIIdf9wou7ZzAyU7s70t7HO6GIr127vWg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-11-01T21:07:31Z"
    mac: ENC[AES256_GCM,data:jX9M2BPo6nxNE46TEwanJFQxLYmY5rmNVwxTX6/77nWBY/IQH1/dCnjyyYIVkq9rlW3TJDTNTPI4vhq7zATOSLPRstNbJ1hBi+IZSsovvHaBDB7aYvMkMpXXpGWMttICwivhJudVg41RabFGSWOyMg9HBNB8cVJ70UsPEf5w8eQ=,iv:R+Rcot1+OPrH96uM8VdIp2fIgxsHHTwUg299iOOWLvo=,tag:tOjj98bXCapvWz02Ms/eug==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
