apiVersion: v1
kind: Secret
metadata:
    name: openldap
    namespace: networking
stringData:
    LDAP_ORGANISATION: ENC[AES256_GCM,data:tXjoAGcZDCN+Df81,iv:KAAI9ZBwH49s+bg0u6CIIje747F1+b01Lb+L0kIjBzs=,tag:uLNnH7TELvVWdzEuJKQGMw==,type:str]
    LDAP_BINDDN: ENC[AES256_GCM,data:uFwjvo/HWu6aEJNAwEAPxlDyshQPgW1M+qbAlg==,iv:Ek7kqMQ6fpYKYnDdMxkn4/ovdBvhbgwh53ryEHuMaEc=,tag:hbB/3k5V2lF9EsYbomsh/A==,type:str]
    LDAP_ADMIN_PASSWORD: ENC[AES256_GCM,data:OlxV1aaUHvBwIpMoybSptldhZ14Q+NEUY/qcUfIsvXQ=,iv:ssAe65RxkWLBFwvT4PmcyZ8ec6FXxFcdLtMLTLt8FnQ=,tag:QhfS0boEkACXLVI2rtGF7g==,type:str]
    LDAP_CONFIG_PASSWORD: ENC[AES256_GCM,data:e1yoyN6E1mKbvGEUJIedHJi7/ibWYi1t/YO0EALixpU=,iv:tSRxsgREm6THEZwzM4N8Uj7eTipZ1Tmc0hTPsnVlfXA=,tag:5BChKj8BWGt8HW7NS1PLPA==,type:str]
    LDAP_READONLY_USER_USERNAME: ENC[AES256_GCM,data:H4qhuVVx3jU=,iv:X5YcETj6ibk4d73LkNmTxvTWdlNhJm8BYm/CdJmiL5g=,tag:wDRReOQdH/V1KPd0Ctku0Q==,type:str]
    LDAP_READONLY_USER_PASSWORD: ENC[AES256_GCM,data:BY8VbwF/P2o8vd4FUIbUMMZ+NMPjhb8UJQu8wPGepdg=,iv:sLUAe+H6CGGHpBktmJaR6ViTV5rLh8jJ7FOG9xMSIM8=,tag:PWaQlTp+kWorXsLtEExgFg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17cmuq9q08fkx2vd0crtmly4vlzwllf6lj83rwsvgg4p9rt0fxa5s0t0xtw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByLzZHeVA3Z2F2KzZxZFdM
            YmZoTVAyQ1ZqZEM0d3NNbDk3L05NTG11VEZFCjlrcFZGUEpYQlVrM09OWFhCNk5i
            cy9HSnJ1SkdyaWhCeUJXOEhGcHVYZkUKLS0tIGdJcDhESXlaTFJrTjRwNjZPYVV3
            dEd2MFZBV3IyVXlBeHh1SWpMclV3ZEUKj+4mklgn2ut7WuuWNlK2n6RrN9zHIRsn
            hpWYbiKp4YTcCGX9aNlTJIPTDen2j6BowtrJocsPJAdbHS2PX5FIzg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-11-06T09:46:52Z"
    mac: ENC[AES256_GCM,data:ezM7ZATReuu56GuUMWkfMrB5VRQBD7HyniaLR3cNMV994W48YAAVef8G/i48vmaRIKBLEQeyOIHJnqoaeVMKA7XnwmNkfcGzhIGznxzyvzC/5VSvkbrNPga1VFUi0y17pf1EudIz77Yhg9d6/0rEBwuIz/D1VRBT7cVW+WC87zE=,iv:oQ9GWbpLLYiy5Iz6MmBJjTtKVTI3i3cLdrI3qtySw1k=,tag:rrsJaidwNGfOb9eXhARavg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
