---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: authelia-postgresql
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      chart: postgresql
      version: 12.1.2
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 5m
  values:
    auth:
      username: authelia
      database: authelia
      existingSecret: authelia-postgresql-secret
    primary:
      persistence:
        enabled: true
        existingClaim: authelia-postgresql-data
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
