---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: jp-gouin
  namespace: flux-system
spec:
  interval: 1h
  url: https://jp-gouin.github.io/helm-openldap
  timeout: 2m
