# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: authelia-postgresql-secret
    namespace: networking
stringData:
    password: ENC[AES256_GCM,data:ygcnzNTGpGGiP+80M9CmU2R4qNq17FO6veCiVp7/WinEzijEHMBn+CoTex2Uaiar6lBwG393jrIybOhL2OE7mg==,iv:oiisreAZvyskRh4R10DX2d+V58ET0Jvhwg0AJAwlWXc=,tag:kzUk7O4XT1YRilrKf8e9jQ==,type:str]
    #ENC[AES256_GCM,data:QA1K6MlBM4hwmHoadrmGB1/qDPq88SeWzu/pMTI9GHSs3LxowR/l03s15giTe3shOINQ41CL9CmCSsqcrb/W22Z+pUryRu+EHd7b,iv:604AIBQUGQuEUh+WEk76793jbaQiw/PsTRSxXTnUm9w=,tag:nwFClMXgaUP6mw/uqwz9qg==,type:comment]
    postgres-password: ENC[AES256_GCM,data:txDtI0a/LWj6AOrffjsflo2HsAkFcFVi/TOOq5iEx/qNCX53Hw88RE7wVKn+gWN2O/lNZ8OTdyu+V63ewgN3kQ==,iv:0dRUFxqwoWGDImK7bV83Hj0Bwjs7w/bGbua8LwnXVRY=,tag:vMJ9koS3f9klWNG5G7HYZw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17cmuq9q08fkx2vd0crtmly4vlzwllf6lj83rwsvgg4p9rt0fxa5s0t0xtw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmcy96eWhXdS9RbTJGcjll
            L2wzbHhBQUF5dVk1WS9NNnUxUnZTRzNtM1dRCmQ0aWQyRjl5UE4yekpVMkllNnhO
            V2JjY3RMYmwyOEcvbllyQ05pRlhOZ2sKLS0tIFBoT2twcHZmcmJrbEdLazVYcjVa
            dEZRMFRKUjBCaEUzeStvODMxc1V1TmMKCZ4biMAWEPtZk14/umUO38I9VKbQOuzS
            FNdEaWRiZIJseKi8F7CjgagEYq+xSbMbvAv0JUdikeq+1+7J2rw4Iw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-11-12T16:30:42Z"
    mac: ENC[AES256_GCM,data:BqYi5Y0kAkxL0OTYXY618R9urNcD3hRjDAid6s0fQ4/N5R/fShenrSR/2Oj7SWAtzYSX6Jr3/fZA2weBmT01HBU+xAc0pEHo3JVnbkUcFfmaTJd11afMWu/leFyggjwq9FY7uOrdWg8DdaPcS1JeQmV486E3K9Sh2RfX/ZTX+vk=,iv:N7sD40U0qWuH+4xPLmT3RD26CjUkZlVM8a3lR+uIUxU=,tag:maT3SEbcXs1ralh510imnw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
