# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: authelia-secret
    namespace: networking
stringData:
    JWT_TOKEN: ENC[AES256_GCM,data:KZAeyiuGVYMAw+aU6wJ6QcMVLvBTz7op5vQH2B7ChYxsAEpF1X1SjGXP0/Kg6H5jDkMrWkeUd6rwmTiSxL5hEw==,iv:pBPnkqJQnAOoz8/l5SY9cggQzrJN7D8T0V8Kb39BzDY=,tag:t7k/oP2ID62EP1GAzUllCg==,type:str]
    LDAP_PASSWORD: ENC[AES256_GCM,data:ZdJ4uni3A+n+Yrehhwz22E6lQZbAg0N49/CfPMZkYik=,iv:j+IX3JS+5//vuC7OYgrl2SlV2IN5D213gjMk/rQdgSY=,tag:tx/qLKLd/tD9VY9xde6vyQ==,type:str]
    STORAGE_PASSWORD: ENC[AES256_GCM,data:DOmkZgI72+TOXlgmraMhjkSYbamSoKQ5H0r/62Mp3fWWROlBDnz/Nkzi7Wkh+Gfhsp7LfJNftxZseWw1Te/1Dw==,iv:CEDgIyEt55NLFWIeUuOv11EkzwUio0NblCk3j0BN7Qk=,tag:baafqiTV9P6M3dGdirNC0Q==,type:str]
    SESSION_ENCRYPTION_KEY: ENC[AES256_GCM,data:D16rby5NpiT71ZB3RiGYybdm6nZz8uCXIA0y4oS1jFdqRyXrPXw1AX2iIPQZr3V2rd4riTrMpOKT6H6RHA8ntQ==,iv:1x1w7Wz6BfPQrS++W4GHUiK/or/O3YfmHS7650wdLCA=,tag:P5Qv6SYvl8jAjrOVRs4u3g==,type:str]
    STORAGE_ENCRYPTION_KEY: ENC[AES256_GCM,data:q2s+/88WUrbKrXftiHrQ4ofGEV02lKt4K3tRVnpTDGVLs2+LKg/vGozNZAPHLxbIOevVTgnUeVkTSgcWneiX0A==,iv:7XHwfo1Q1DWZp3V+y4jf3AQw8Oo/f3PkD6XgcipwRa8=,tag:Cngcc4bISOJl7g0u85XbFw==,type:str]
    REDIS_PASSWORD: ENC[AES256_GCM,data:h1jxndNdWBMy8iOK2C0dhWxTN3nPSNHB4iQvsOV+Xtm7uPL6XWVwyt+Ozm3N5q3QPseEzBsAptyMlmmgL156bg==,iv:Rh0HN7dZlFa0FxIH1+WYg7cRKK4sJgjXXun1p47WNiA=,tag:4N7D+iSNC88/j0Et2zVUfA==,type:str]
    SMTP_PASSWORD: ENC[AES256_GCM,data:yTiCoTlq9eSjvKAYdnNGUGT53J+T0FrxuOZzNaFZRuuO2s9fCANIn2Q/gvHzvAwuGtX0biavo5TMQtwZROcUNg==,iv:EULKfIDFr+pkOJTS45cHhGLNxZp6sWC/9fpib4f4qA8=,tag:holD//ljNf2IEVqL8MjRSQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17cmuq9q08fkx2vd0crtmly4vlzwllf6lj83rwsvgg4p9rt0fxa5s0t0xtw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwY0lPY0hJSGN3UHZ4aitm
            TW5nMytuYVl2NXpXdW5zc3QycjVOcGhXcHhzCjBvcUs3T1RJUWhaM205empQVWN0
            U2dLUWRmaS9sbFBlRXFtVVpwbitxQTAKLS0tIFA2TG92bFV6SHNUNkpXRTN0OTdq
            ZSsvUkNpZ3drSUM3ZDM1SHZ6QmNEZnMKb7U53+dzJkd/TbUUviCVa4JgtonEIV8Q
            XKuH6768K6Owplw3OFpwvX0Pj1uFhODYlqFWNIQHrKg+0xrtvbLGDw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-11-12T16:30:42Z"
    mac: ENC[AES256_GCM,data:tlRe55kmiiWD7DtGqAFGkjbaq1+dLH+IlnYR6mVLo0Hssec3U5WbNAJl4MkgoGUbRdlpuabRnMGOEtXG7KwRwdo6RuBvgbjyPjkl+Qak5kv9gfbkfKawtVLIWg0Wraq1kkix4zwGawDivmA3PbDD/vtm7v97kH1gO+yVtr9PFSo=,iv:eack5sU3cUiHL9m4wF7YEyNuEViN99pwRa08ut3V9d4=,tag:AaLiPakDSqARH0MVTbFfkA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
