# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: authelia-postgresql-secret
    namespace: networking
stringData:
    password: ENC[AES256_GCM,data:6CPVs1cO8XNv0sSss/stQ/fz0Sg9fDIVgO6VtEkKJQx35ClyB78ENKtUpcPA6ceFk0LcljUGYVBic3TJNypmyQ==,iv:0YOGUjSGjKCXjWJ4j3vzrxeVOOKpjbI61SYZMqwRiG4=,tag:OoAoFY4ljaoE8tMv8fka6Q==,type:str]
    #ENC[AES256_GCM,data:IIKg84verMA+YVF2XvBc9u4svq4JoaXIyN50835Mf1iZ8OCYr/SUYzexeEko9HZXtoKApwsACaQlEOalrbkkwH9RLsX5C3FQdhws,iv:77IJ8mZbk2ZIQ/E4NBU4YbwLeTPlR9rPlAuG97E/dhE=,tag:hutMSk5KfBRWP0GfY+6eHg==,type:comment]
    postgres-password: ENC[AES256_GCM,data:TQCBCutINT0AsjpLWKDR3y3sKkW7nvzZL6RZL7aEvfsDReO3PvuiQYvEKQMXqtUMSLXzcMMHEYI73SMnRK0eHA==,iv:U5UF6dA3kJ1c8Vh5euInMcxNVkODe4gbofhqmPAJ/f0=,tag:9nomSdIe1w1GK/9YvVmEMg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17cmuq9q08fkx2vd0crtmly4vlzwllf6lj83rwsvgg4p9rt0fxa5s0t0xtw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFWW0wR2wxMGhyOHRrMFNE
            SFBVYkxXdUhUOC9oSUxIeGkvbmlQajBRNUdvCk9YdzdDRVgzYnVGSEJNUTIwTGxM
            YTNiRkZrK0N4cTRBRlczSjRpQWQ2ZkUKLS0tIFk4U0Q1aVFRL0ZhN0tIdC9pMmMw
            QlVsVEUyeWs3dHI1SFREN3FsYXB2YmMK4zNibN1JAypnS4+RX2AgGrT4pYfpDORa
            TxMh2YysNdwEM2WPYXr+F3bkUsn7l8nZ2bxhwX+SaVvR4B+/N+rp2g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-11-20T20:24:52Z"
    mac: ENC[AES256_GCM,data:83jsbBInvagVAV0jnVdFQSaraRW3UMMnxjr3VtxGv6kyI30PMySH3+1VHCzXxEZJSjSp/FtwTaeqZghBhnIZK4BM5TeLDlql87B5r7/jQaLcr6PXDqvhI42xCTgkzT/frD00bGgMIu/PiEnHfWVEK4LLdDvFAPH3GnNdQ5V8RNk=,iv:tCOEVmcqNoNNxNCPSU+XSnSob1XrOEKb7a4M1nwQHAo=,tag:1Y6LpxmCVw/qNaoFry2N/g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
