---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: goldilocks
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: goldilocks
      version: 6.3.3
      sourceRef:
        kind: HelmRepository
        name: fairwinds-charts
        namespace: flux-system
  values:
    vpa:
      enabled: true
    dashboard:
      enabled: true
      replicaCount: 1
      resources:
        limits:
          cpu: null
          memory: null
      ingress:
        enabled: true
        ingressClassName: nginx
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-staging"
          external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
          external-dns/is-public: "true"
          nginx.ingress.kubernetes.io/auth-url: http://authelia.kube-system.svc.cluster.local/api/verify
          nginx.ingress.kubernetes.io/auth-signin: https://auth.${SECRET_DOMAIN}
        hosts:
          - host: "goldilocks.${SECRET_DOMAIN}"
            paths:
              - path: /
                type: ImplementationSpecific
        tls:
          - hosts:
              - "goldilocks.${SECRET_DOMAIN}"
    controller:
      resources:
        limits:
          cpu: null
          memory: null
