---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mailu-storage
  namespace: kube-system
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
