---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mailu-postgresql
  namespace: kube-system
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
