---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mailu-storage
  namespace: kube-system
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
    # StorageClass "local-path": Only support ReadWriteOnce access mode
    # - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
