---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mailu-postgresql
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      chart: postgresql
      version: 12.1.15
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 5m
  values:
    auth:
      username: mailu
      database: mailu
      # password: "${SECRET_MAILU_DB_PASSWORD}"
      existingSecret: mailu-postgresql-secret
    primary:
      persistence:
        enabled: true
        existingClaim: mailu-postgresql-data
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
