---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager-issuers
  namespace: networking
spec:
  interval: 15m
  chart:
    spec:
      chart: raw
      version: v0.3.1
      sourceRef:
        kind: HelmRepository
        name: dysnix
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  dependsOn:
    - name: cert-manager
      namespace: networking
  values:
    resources:
      - apiVersion: cert-manager.io/v1
        kind: ClusterIssuer
        metadata:
          name: letsencrypt-production
        spec:
          acme:
            server: https://acme-v02.api.letsencrypt.org/directory
            email: "${SECRET_LETSENCRYPT_EMAIL}"
            privateKeySecretRef:
              name: letsencrypt-production
            solvers:
#              - dns01:
#                  netcup:
#                    email: "${SECRET_NETCUP_EMAIL}"
#                    apiKeySecretRef:
#                      name: netcup-api-key
#                      key: api-key
#                selector:
#                  dnsZones:
#                    - ${SECRET_DOMAIN}
              - http01:
                  ingress:
                    class: nginx

      - apiVersion: cert-manager.io/v1
        kind: ClusterIssuer
        metadata:
          name: letsencrypt-staging
        spec:
          acme:
            server: https://acme-staging-v02.api.letsencrypt.org/directory
            email: "${SECRET_LETSENCRYPT_EMAIL}"
            privateKeySecretRef:
              name: letsencrypt-staging
            solvers:
#              - dns01:
#                  netcup:
#                    email: "${SECRET_NETCUP_EMAIL}"
#                    apiKeySecretRef:
#                      name: netcup-api-key
#                      key: api-key
#                selector:
#                  dnsZones:
#                    - ${SECRET_DOMAIN}
              - http01:
                  ingress:
                    class: nginx
