# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:w5x2nQsDgNhnHNxHAQ==,iv:08ttKkoXbNWkalEHN+GA5AZnq9I2hyfekNBurHROMQg=,tag:5mt/R1JnbfXYeF36AidXOQ==,type:str]
    SECRET_LETSENCRYPT_EMAIL: ENC[AES256_GCM,data:OC5ajd35oRFb/NX6vwFB6G2v1QxVs7yh9Q==,iv:n257VQmsVlOh3N1wMIlQeu3LgxcW7I1ApEfHoLbW0Xc=,tag:zK9fWLPy1U3JhSotwLIRcA==,type:str]
    METALLB_LB_RANGE: ENC[AES256_GCM,data:vyaH5O09zUAtqiU1t/M=,iv:r6tvjGLPAJURmr+PhLSNFCcQlUN0NpuI2GY3keohHUc=,tag:JNjUvf19oVm4VpvidmIvGg==,type:str]
    METALLB_K8S_GATEWAY_ADDR: ENC[AES256_GCM,data:jetyTDZ1Ym3djPpasFg=,iv:NUZsCr6ka7jKROnmd5ltUKVol63bxWHe0dX/9OZw0hY=,tag:MAbtqAci6n8xGqecJxOlmg==,type:str]
    METALLB_INGRESS_ADDR: ENC[AES256_GCM,data:I1R/p6bvEthklhKSHI4=,iv:k+3CCAh6514zNxz7MI+KmoLmcVantI0FSDmGnAKcmqI=,tag:wpT4fJLxqsvjycDVBqJCuA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15uzrw396e67z9wdzsxzdk7ka0g2gr3l460e0slaea563zll3hdfqwqxdta
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBweHE4dThhQ3Jkb3FtWkpm
            OUtaLzdCc0tFM09hKzNXbFNyQVprcXU2QW5rCmltZXg0blpIVDRabDZNUVlmZWx6
            amxUNkk4ek4raVdIUEhkeE02SkRJUGcKLS0tIHhzek1WekkxeXhxcFkvcjh2TFlo
            cTR6a3g4L1JpZG1WVlhaVjNXTkd2cFkKH/sC4zmNy1CgVyUSbFIIOO5KIkJY579T
            0/32YWqvr7LpQI+kA8OxL9/NkJQfvkB4ztJS/0ZnJuT1r5RQm2bIug==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-10-30T12:25:10Z"
    mac: ENC[AES256_GCM,data:VSQ5CF+CZzRy+KbRb8qrBGa/KDAIcBjImUD7RLoMoY4H2xlqpKTTp2sHU2ri/z/BUge9JtNjth0c83dyTU39cLZ6Pft1SbzzoHfIM7baLjJJUw1VIKw5IIaI79nrcA5QRzNOWDSrhkXn1qNpcFPMn3+WDUiImyHyvhNgGhxRoB4=,iv:xW+mQ3Sse6kGKGtix5+/7/Q6fucToCGnr2qQy4OWmMo=,tag:W2Fy/m9n5zbEJ9QPDl9PjA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
