# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:p09Ps83P7ynRh/IMTw==,iv:qZtfSK2QTsSdnFeNIlLc5iLxl5AlytIZnihZnchm5RY=,tag:/FYK0PykBvEr3w9J9d9q8w==,type:str]
    SECRET_LETSENCRYPT_EMAIL: ENC[AES256_GCM,data:vdZkD+pdaU1OQfWDhBRCR/Iclj46l3SeLg==,iv:8IPm0jcTDPjhdQtDGWBwS2yxICu2Z3Cpy+QRMrtsbkw=,tag:2LMiCTMYH2BrEmAdQkOh3w==,type:str]
    METALLB_LB_RANGE: ENC[AES256_GCM,data:q9mQ2GS6Xh9voCy08vE=,iv:hrPqbY+m4QSk1oo00zndY7qSGLRCiNDles4X+zYgjHY=,tag:cqIEMPSNMEppgjZZZyBDmw==,type:str]
    METALLB_K8S_GATEWAY_ADDR: ENC[AES256_GCM,data:4aAK5Rws3vDddtRqCcg=,iv:LMA2qnvf1txOD8STun+YgItFFdl4u/TUukomiMPefDg=,tag:Dw1MS+qqEpzoqieGV+f38w==,type:str]
    METALLB_INGRESS_ADDR: ENC[AES256_GCM,data:IOpclhg+fZQWo3IDc3w=,iv:W/Yoms5WVuxflqAma439Nc02PaDAWB4SLE+ViYuJWB0=,tag:B0mYCPxWwbs0TtHJ/6sUgw==,type:str]
    #ENC[AES256_GCM,data:D+OPjL7JGWRwRkKabVo2HdxUFW7yCyE5n+TwThoh3atgR3dKSPvy8bQJEWqIfeVAY4KPdPvIL9IPcMGiX803Oaamp+15yE3+Q5CBOw/nJ7gxhwThqHSBmOpzItOVAg==,iv:QxKmJ5DBxnstax/NV8JE3Rf/szn5lj7MJBja62iRB74=,tag:euFtKOViZwSIgfegtlZ/Lg==,type:comment]
    SECRET_AUTHELIA_LDAP_BASE_DN: ENC[AES256_GCM,data:xO52fZWAls6cDf1GAWAE5HGfNw==,iv:Lt2WDcfdg2s3NBipwCV7Y0nJEkPt5IH2/HfKDqt2/nI=,tag:tm9KBRWh1Mk6JCAEZnDzBA==,type:str]
    #ENC[AES256_GCM,data:lL6tDqfquwN4XsibcNoEUPZvsbYj7cm2FxDPEYkMI9CA/0M7VeT3R3uI7qfyQ3a2GD69iQdQcVav9A==,iv:35uOrXaJuc+xv/e0OMQ7ZZ3591Gtc/gDOHwDq6xPZqQ=,tag:4tFk5yG3R/nY45dUKscFyw==,type:comment]
    #ENC[AES256_GCM,data:srKpOzDQ1HR3CatQWfw8bRCgCTV8ThF1T2T1/+gqyAMfPazFHhIWGDrYyOsPjjFaQ+zNSSFV/VgUfQ==,iv:8nhiR7J4lOQNflNLGLDUeX2U5sfJcLc0rp206A5MCzY=,tag:p6S7Bxxy2yqNPCs2tp9SvA==,type:comment]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17cmuq9q08fkx2vd0crtmly4vlzwllf6lj83rwsvgg4p9rt0fxa5s0t0xtw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpL0pJSU5hc2cyOTZLVEZV
            dGlKanJ2L09wRjl4M0UvMC82RDUxbWVRcUNJClNNcDBtdE4rck5mSUtrS3ZXS25V
            M0ZVekpsOGw2b2s3bE5BcFVpaGhlS2cKLS0tIDJJRFdmS0Vld3lob2Rrd2Q3bnpV
            MWFrU212R1pHZUY4QjNmT3ovam50SGsK0P+mYtigOsc71IiZ+wFwXkVe3pbw3coE
            jenvm4cDo0XZlRT6sINNLREYJacKDyf+7+8Tv2mTdbWMKqa/u+PU/g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-11-12T16:30:42Z"
    mac: ENC[AES256_GCM,data:j2Lqs/0bU1bs/vqv1VaEB0fFE6hOrAEipSLbogwin10OOvQ9dEt9T1KqhtasF4Za6D81kGiTQSwsiFIjXCnKxQ00b00VFvx6EJXrrUgmvpdQx29krdDFw1idvoEeZi557IO8vmjsSGjlyZDuHZjcfIzzXHaZyRqJM7JA9OB7BrM=,iv:8Hhr3nN0LkN59HxI8SFimca94cnAhh5p6pnihek7KFo=,tag:y2LNU/QfqCaW0SbHhvLAZQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
