---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: Europe/Vienna
  # SECRET_METALLB_LB_RANGE: 45.157.178.195
  # SECRET_METALLB_K8S_GATEWAY_ADDR: 45.157.178.195
  # SECRET_METALLB_INGRESS_ADDR: 45.157.178.195
