# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:lTUxhe5okt2oeB6WCA==,iv:qwRjR6lRcGRakXQFCpGCfIbBONf78ec/KrKI03z82zE=,tag:QS3+x+18NIdAYN+0PL3vPA==,type:str]
    SECRET_LETSENCRYPT_EMAIL: ENC[AES256_GCM,data:7MNLnAg2bZJyqU4S+VIT85tV7S/bs/Y87w==,iv:kOvnlC+dg3iliuGNnLUOoy0kro6PrsT04gBHW6n5YyA=,tag:A2Dte3zyICmz4gBiem53RA==,type:str]
    METALLB_LB_RANGE: ENC[AES256_GCM,data:Wpz7JJkvcEL3LQULrXk=,iv:TyGQRX1A+2JtdXyMk6Wb+oItr9c18cFleVkDVBBKNNk=,tag:QwrwPmjlvXeDikZ8Lv4KnA==,type:str]
    METALLB_K8S_GATEWAY_ADDR: ENC[AES256_GCM,data:cTvkC0o/M3IZj5RpI5c=,iv:uEFT4QGuMGFxHJMmcoT5SvV9EF807X6Ev/ZtngR0ctI=,tag:aNKLROvre4+PVEwb6O6Xvg==,type:str]
    METALLB_INGRESS_ADDR: ENC[AES256_GCM,data:EOehSGSwboWzZnHZa9Q=,iv:9DYqnKQzHNWRMiN9CxYhtfXX6McvwzxPaqf0ZiiOIBA=,tag:aoThAtemnvyD4fTyo7p3ZQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17cmuq9q08fkx2vd0crtmly4vlzwllf6lj83rwsvgg4p9rt0fxa5s0t0xtw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJNjBFSU12MThMdGo1cjI0
            Nlc0eTgzeitONGNORXNCKzFkVFk2NDVuY25JCnpkU2ZrcWhsakFqZ2Y0OWRTeE1o
            azRyelE3K1J0a0pUeVdGR2cyN2xpUnMKLS0tIFFZTEd2Y2lLbFdveG9yNmErdHB3
            VjBNZmcyUEh3NkRmNlI4NHJmazJmbXMKP3tf+wOv8DGoQXgredUD+p7xSn5Yg4h8
            ZPUFE9+uO87+aY7bdAf7LpWQkjc7UH3ZWIs3dmElEakhJw99iuINEw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-11-04T13:57:56Z"
    mac: ENC[AES256_GCM,data:3mz4roR1RwnuCBVmKApq3O3AIeSuO+hHMgnjcgqmmFM0AEE6xN0fI7EeuUr87Ape9PsCobObjuIAaAI/K9XMicsTIj66DmYGgBF0MGzL+5YRUAzL92rqanKUemdbehDX+7O3oMDexyb2XZQ5/urmCV4KUvhAuHUuyge3KVfysoY=,iv:w5+zlKzkl6cTo2vNlWwMrX99nprbMaqSTZ+b2T/roAM=,tag:XUZTdLNkepkJsUnrtKgYuw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
