# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:Mash9QRWu0EqtL143w==,iv:o8a/kS2p99LCxmCY2JcmvEQ9aKR+9UFSBhK3MSaqOCs=,tag:3npdcZP6RVxHAsK6qzXQYA==,type:str]
    SECRET_LETSENCRYPT_EMAIL: ENC[AES256_GCM,data:paFnyEOQRdDsOoRrSZSI1L5rU5q5sLh+Kw==,iv:Shhv6JtLTlmg00aM3krvKZ9aQFo5Y5i4Dn556FKhsXM=,tag:S/zMV2Az2BrN1RyeObR69w==,type:str]
    SECRET_METALLB_LB_RANGE: ENC[AES256_GCM,data:BoSQ6O3H/mwi6S5zJoo=,iv:5STMN9um0bpV8iMTgOnzutPzik5GkBKNAMA2FqF37Fw=,tag:w7BvKV/+e1RZWYNmci4H+w==,type:str]
    SECRET_METALLB_K8S_GATEWAY_ADDR: ENC[AES256_GCM,data:89PtSR3GwHUgigzC5UM=,iv:w0wMpeIL3Ng2XZBBYktSsH0qsV1Y6NpxaUayad/aM9M=,tag:Gfk/Yi4Ezql8m2mHfUhW8g==,type:str]
    SECRET_METALLB_INGRESS_ADDR: ENC[AES256_GCM,data:cOoZTsT0p01otyP+t+Y=,iv:c6Ie4IGjeGS0pB5MN5iTUf0WI7Qi7ih+XBDp8B/F6FA=,tag:I4z1c+iNTdu7HIQGElcGuw==,type:str]
    SECRET_RANCHER_ADMIN_PASSWORD: ENC[AES256_GCM,data:526xPk8bEzApAqcfclfG1UAItsQp8gAouIEBoUsPROkOV1wQh0vd3IZPN859+Q+PV5fpz+YN9aSfuzaKTw738A==,iv:DsPxemOrjCgm/Ja0gOENvrQSwcbn73XVT260ISyukhc=,tag:6Rywm5T1vnLJ7INu4Foh9A==,type:str]
    SECRET_LDAP_ORGANISATION: ENC[AES256_GCM,data:lO8pv6Brs8CW4222q+F1NMh8kQ==,iv:UXodPWO+tZYO4jTnDKi2aL8/WBPUs+fOX1qdSbxzK5Q=,tag:KMYoOVyit1yI9KMXLJRI1Q==,type:str]
    SECRET_LDAP_BASE_DN: ENC[AES256_GCM,data:QuFaOXM+TOEJBC07Ib5ZcjB8Mw==,iv:l7Dm97r2PEabRfitLYv6kHv9gEmS60RsHXOwbjUtMVI=,tag:mlZZaDUyfS5ztFbAYhFK6w==,type:str]
    SECRET_LDAP_BINDDN: ENC[AES256_GCM,data:ALh1sD3u6uvfH4rU2gmzfWi9Qkgdsw6auFn/7g==,iv:INuQmoV94fdkfTlMw88DV9vK+hGF1ydPVP1+I84iFxo=,tag:wuSQ57Sxc0mLwbNeb1q7IA==,type:str]
    SECRET_LDAP_ADMIN_PASSWORD: ENC[AES256_GCM,data:7u3Pwy1HNpRYu/Kp4dJVW/i2GhWDLQa2pUFrDaUoCuDBZlOdu+T+0qxhydKr3jcFFAPnOMLkfXWoHF35bau25A==,iv:tbIITVDKA9VEV/H1DoLy+mG+UU2zdcH341KbOBJIFjQ=,tag:4xOwSysGtbiGtrDi9CrtyQ==,type:str]
    SECRET_LDAP_CONFIG_PASSWORD: ENC[AES256_GCM,data:hjHd9/+tFNRJqaZOSDVElJv+p7LAm2YxsIt61GPRriowfl/oQiaTdQYAyNWdy+WSYrVMD0hu5VyAlnMP5mIgvA==,iv:tVLiPA7eWdasO9+mq6liz6nXW+Ag3A/6QZaLGPupEek=,tag:kVnVy5xa5J3h5WQ6LYmrXQ==,type:str]
    SECRET_LDAP_READONLY_USER_USERNAME: ENC[AES256_GCM,data:xEnWMgGodBI=,iv:E+IdGHdL4Pkgp9G2vWWtGvZpLbiDOdZ4wM1xhwBPmns=,tag:cI8Ruk6gGWSRtcuihWyQvQ==,type:str]
    SECRET_LDAP_READONLY_USER_PASSWORD: ENC[AES256_GCM,data:avv9TTigiQIRhdepkEfvCWc5/pygnhQRpR5Wn/8jTnVotubUVNcz1/22s6/p5hIGkWsEb4zT5bu/cf3Ccl+9Zg==,iv:4okx6C4H4Bfzc7DUAEAAcyzHHXTo4lvgo+gFqJe+cok=,tag:9l4S6jn+k42dX+Ri4zppkg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17cmuq9q08fkx2vd0crtmly4vlzwllf6lj83rwsvgg4p9rt0fxa5s0t0xtw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4aXkrUFVPS2lMWTBlN2dx
            RUlqWjRwTXhaaTA1VmM1ZmUrOU51V0VMVGxNCmF6UVFCbDU2ZWJVNm8rSzhOQW5S
            OVRsVHphdjYydklXK05xWEpLeHNhTFkKLS0tIGFBc0JTcG94ZXVUSURqdHBPQXhy
            TUdQYmwwVDBpaE1SN0lVNU4vb2h3OVEKtfotFsltiMo7dv+JI2ZRVORdHwC22qgR
            c2J+Hl/utQXL6q76ZYqpl02bLw0N8ZmpfQkJpuhHWzIwJUlkcmUeXQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-11-27T17:45:35Z"
    mac: ENC[AES256_GCM,data:vF7fs9pHX8cC9KnPspzcQ5SzId/5kBLajSGi21tMhfYxc1W3rPcDOaX0hljg+Ifp41Aps7nMQjNkTBIaIU598AOgIf7/i09ZnIhMqDK5z1a9R5KzVEmfu78+0sN/sgAcNcS77PESwvK+f+/EHEtCD3yeaxM/+YHIFls02OiT3zQ=,iv:SWB77cRRORDrvv2uhg4fHi9RCaeiGBA6vYgHooBrHLk=,tag:snqqu8behsiWvc3NleTbTw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
