apiVersion: v1
kind: Secret
metadata:
    name: lldap-secret
    namespace: networking
stringData:
    SECRET_LLDAP_JWT_SECRET: ENC[AES256_GCM,data:ZrMmQGPzxJSfa2Jl+wqk1b/vB67L4A==,iv:8OEnH/tfxmH/V/yfrU6txolhvs/7g349LKbi1zDDqaM=,tag:XARlaKypDQwDlXGtsRA7vQ==,type:str]
    SECRET_LLDAP_USER_PASS: ENC[AES256_GCM,data:uQyaH1lIuoPeZhvAU3OKOPXTBaWAQ2mLiS4BLpLl,iv:ZNLgO6eh/PIyxJAtNuCIUCqPkoG05FkzBZzuYDflWBY=,tag:arvzys5e9PArK07RTJDY/Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17cmuq9q08fkx2vd0crtmly4vlzwllf6lj83rwsvgg4p9rt0fxa5s0t0xtw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByelBKeVQ4dVJYeTkwTXFO
            eVJaWXVYcVpvZXBndWFZVXh6TzkvbmY5N1VvCkp1ellWcmlidGFSK2FXdUp3OUlM
            R3FnMWJVWEYwdnNENHdxa1Y1d1VvK00KLS0tIEFaNDltbWJhcEJmKzVzN0p6WVg2
            NXBpQ0hqTXdCUlpIRkVwZTNSU3J6OFEK8sE1HwEurBeI+7ZvVS7csjfqxoRanICA
            mLNXlZfEJg1WbMqvhjLXAGoeFuQ03h/suI9dtwdg800DZw892o/FmQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-11-05T18:39:40Z"
    mac: ENC[AES256_GCM,data:0ahtmXLSXaIqv10ZkYh6+d71oya8NgKrg2dYGD5lxSlo0Tdyh2ABZVky79xo8HCrbYsarxXN/UZs0Pb0T6IzDbzAvMhmkKCyNagrTE1ryZd8ls6dMtshOXGHBbI4VyRCr1hQvyCeaPBzitvgYwjPfIw0X4rEkFoxK9JaG4TFZ7k=,iv:6Ql32eRIOH24WlFyW94U9v+lyYxQXHJ9OYdmVstxnfw=,tag:eu6nQ4YRrKfB/Iommefa7A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
