apiVersion: v1
kind: Secret
metadata:
    name: lldap
    namespace: networking
stringData:
    jwt-secret: ENC[AES256_GCM,data:ODfs5orSQoeKU2Hnd3dNrRJYCAL4WQ==,iv:y9X5CDqABZFZCkT7zms15jj4XtGO8VyWKLJj1Z0Cx3Y=,tag:KuuJxp9mAiUxcNQ6QI7ySw==,type:str]
    user-password: ENC[AES256_GCM,data:L4ecyk7M581pt9TT/XWnO7I95OtIhJGFGNwrQuc+,iv:TRuxG2iPRcjNjFBIhozioAReraXAkYHbJTWcHfk/ip8=,tag:NF4us7sB6WPusP4xHDcQCw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17cmuq9q08fkx2vd0crtmly4vlzwllf6lj83rwsvgg4p9rt0fxa5s0t0xtw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZVVh6Z2R0a0FCMTFuZnF3
            YWZ2UXFPYktVZGtqaWh0cEFRTkEyYWFRY2x3CnRScDRuM2NBSW9aaDU4WnJQbkRK
            YW8wNDBFREFtWTlQZnlwbDdhUHNUb0EKLS0tIGIxSExveEdldDBzZW1ZY0tlb2Jq
            TmZuL2RkNmRMOFZ2dUZsMUhDZGxMbk0Kt/6bowUFXQKC+NgOcXJA7sUtXZ68KTc4
            3hJMVuP3ZxNVAQpQuEnCBYgCgXUHi/sSKGRx10Lw3GKf3k5md48ZYg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-11-05T14:51:43Z"
    mac: ENC[AES256_GCM,data:WU/rI0oxO6ozb+0pIj5Fmrp84jjWrg8EIMDmOEz/dHfplvHxmRmFImgeuGenvvpXiT/TtVO1JTlSAzdyRxpbJaPx1ascnwDbwuV7ZFoqaspXXW2pg6FmyMsd342m1u6jdUGB1Iu/UErPIN+1sgVW3vPDxCoG571BiExr7enjhyk=,iv:3QB9stzXjufhrYpbTv+cu5c4kELQMG0SdnkzgbpLPfU=,tag:QxHbMJA2UULimneS3S+QIA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
