apiVersion: v1
kind: Secret
metadata:
    name: lldap-secret
    namespace: networking
stringData:
    SECRET_LLDAP_JWT_SECRET: ENC[AES256_GCM,data:Ok7P3z9xTUWyZu3P9CFPLAWmyaEjYuZV/3M1ibppIoBSDhLG4zXIZxUDg5tqnsVs39IMvQVOjeBdrSbmd9+eyA==,iv:BVsxafoKDigglguaLoq7iv4nDcsy85frpWRC1yltQc4=,tag:xeC3OuuMN/TYEProBJ8E8w==,type:str]
    SECRET_LLDAP_USER_PASS: ENC[AES256_GCM,data:+jyYyQ0bIAfubLoKIgXhjwlXWpd9AxFFm0v8sG7KScQM9kH679Uh5EEMpPgwppbocx1gmQGm7xzyAgNIF7o0hA==,iv:wl64lUV25FAe0cee+2NdiFrHnyYtuz5Bf8cS6u3YSDw=,tag:Ph6w2juxPDNHrnXAVndqkg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17cmuq9q08fkx2vd0crtmly4vlzwllf6lj83rwsvgg4p9rt0fxa5s0t0xtw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHN3VWZWY0bVdoTnpUcEZk
            VFVJM0p1SnRsbUtqWHArbzh1cko4S2Q1YVVrClFwazJtZEZ5U0VjRkp2RHRqRFk4
            SytrOEtranhmSTB6N3RFYTZUcWU4OTAKLS0tIHBpV0lGU0g2RWRmYldrcVBRWGRB
            aFMvWUxJTmxuME4xOEptNHpySU9RS2cKv5+WoHUh3EqHSLWh3UsH2w4H7FCq3/Qi
            zTEciFgStvqr3JPklNZtF1ADjkvTCLyDjl7VbxNOtXlZeqdKEkvLrw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-11-12T17:55:18Z"
    mac: ENC[AES256_GCM,data:H8qeJqyy7Qr3G7TLbd3MU6pYpt6qmmK2ytYWiR9TBYfNwCCPjsh8LUC3pA5avggu0w0kKz3zJ10aG8ROgV4vL3Lbj3lvpLm7amsBmN0B4ciGUc82dvj8dWnw4df7AHHx696es/hXCVbBtTIvkBQT3Rpe/McftaOVjEed4Ki5qw0=,iv:KdkRu9UzQN2EqmdvCU4hpfkJ0nq8hlO9Wwp7W07zXHY=,tag:cX4cqep8yCey+ER/ipEbTw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
