apiVersion: v1
kind: Secret
metadata:
    name: lldap-secret
    namespace: networking
stringData:
    SECRET_LLDAP_JWT_SECRET: ENC[AES256_GCM,data:OU0lTZl8yW9bLCVOPKMHWF/kIDrzKKtt5Yvbfx3TLSyqOofH3Yez4RgCEXcIwA2Eb2i02oozq9xO2dcDSZuylA==,iv:ySDJ7c9OhLFBDrNufOLgPLXkWWOzVYbBCZaKqtUrmqA=,tag:cuYx9DAkxv3nXQo7C6CvQA==,type:str]
    SECRET_LLDAP_USER_PASS: ENC[AES256_GCM,data:GjV07Jj98UC0TPj+1B6/pzv9y6AadhEqF8Sy2T+LCDkmpRTB6bWgcb0Z3e67y5q79qAM8IVPDxi10U2QXSAVjQ==,iv:ZQHjZoMR9E+ScsBMhwu168dyzUkU31hERn4yEwbuy9c=,tag:GIIVFT1UkQ9YfWlu6g5/oA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17cmuq9q08fkx2vd0crtmly4vlzwllf6lj83rwsvgg4p9rt0fxa5s0t0xtw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhVFh2NFFpQ2hNRzlDTEwr
            RWhTU0tCVnZLMytIV0F3UXN1R2FnZ213RkNnCjBPTmVhaWVMbkxwVGMrTmdLbHF0
            NjRCU2tWaTFWa2xac1Ywd1BMYk9PNWcKLS0tIERwNkZqeitxcVV6bndFbE9qMmhm
            dDhoT0phb0pNa2p3VjIzYkNFZml0YmcKMnBUXQ2IfsYXTMOduR0EvFcraCOPkLi+
            K6Vfwq6rtQ/m7ZVDcZQHNqeRobfYDHSH32BLHqgR/MQ9tXcV56uozQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-11-16T20:42:12Z"
    mac: ENC[AES256_GCM,data:uLmIQ8elripOTyV0ViHdqA52AJTM5++b4sedMTE9ERhrOCwwtG06S71stKEKtphxeGkDysMOgVGHwYx+N5beGmI2UtppBPOc5kmrdQ69ZGvH+sr7PwHgqdPPQ3NBurlWmPie2GiEoVtrCDZpNVYUJX4G3asTi0K6f6u2ryug+S0=,iv:XWc159XPdsVYR2Mo401uWV0sZiUukea6HeIKbvD1Tto=,tag:b4j1IbASZaGRLQ9g+Z4wlQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
