---

# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/apt_module.html

- name: Upgrade all system packages
  ansible.builtin.apt:
    upgrade: full
    update_cache: true

- name: Install common packages
  ansible.builtin.apt:
    name: "{{ packages | default([]) }}"
    state: present
    install_recommends: false

- name: Remove dependencies that are no longer required
  ansible.builtin.apt:
    autoremove: true

- name: Restart node if necessary
  ansible.builtin.meta: flush_handlers
