---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: networking
spec:
  interval: 15m
  chart:
    spec:
      chart: ingress-nginx
      version: 4.3.0
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  dependsOn:
    - name: cert-manager
      namespace: networking
    - name: cert-manager-issuers
      namespace: networking
  values:
    # Configuration for additional TCP ports to be exposed through Ingress
    # Format for each port would be like:
    # <PortNumber>: <Namespace>/<Service>
    tcp:
      # Map 1636 TCP port to LBR LDAP service to get requests handled through any available POD/Endpoint serving LDAPS Port
      3890: networking/lldap:3890
      6360: networking/lldap:6360
      # 1883: mqtt/emqx:1883
      # 8883: mqtt/emqx:8883
    controller:
      replicaCount: 1
      extraEnvs:
        - name: TZ
          value: "${TIMEZONE}"
      service:
        type: LoadBalancer
        loadBalancerIP: "${METALLB_INGRESS_ADDR}"
#        annotations:
#          metallb.universe.tf/loadBalancerIPs: |-
#            ${METALLB_INGRESS_ADDR}
        externalTrafficPolicy: Local
        ports:
          http: 80
          https: 443
          ldap: 3890
          ldaps: 6360
          # mqtt: 1883
          # mqttssl: 8883
        targetPorts:
          http: http
          https: https
          ldap: ldap
          ldaps: ldaps
          # mqtt: mqtt
          # mqttssl: mqttssl
      publishService:
        enabled: true
      ingressClassResource:
        default: true
      config:
        client-header-timeout: 120
        client-body-buffer-size: "100M"
        client-body-timeout: 120
        custom-http-errors: |-
          401,403,404,500,501,502,503
        enable-brotli: "true"
        forwarded-for-header: "CF-Connecting-IP"
        hsts-max-age: "31449600"
        keep-alive: 120
        keep-alive-requests: 10000
        proxy-body-size: "100M"
        proxy-real-ip-cidr: "${METALLB_INGRESS_ADDR}"
        ssl-protocols: "TLSv1.3 TLSv1.2"
        use-forwarded-headers: "true"
      metrics:
        enabled: false
#      podAnnotations:
#        configmap.reloader.stakater.com/reload: "cloudflare-proxied-networks"
      resources:
        requests:
          cpu: 10m
          memory: 250Mi
        limits:
          memory: 500Mi
    defaultBackend:
      enabled: true
      image:
        repository: ghcr.io/tarampampam/error-pages
        tag: 2.18.0
      replicaCount: 1
      extraEnvs:
        - name: TEMPLATE_NAME
          value: lost-in-space
        - name: SHOW_DETAILS
          value: "false"
#  valuesFrom:
#    # Cloudflare Networks
#    # https://www.cloudflare.com/ips/
#    - targetPath: controller.config.proxy-real-ip-cidr
#      kind: ConfigMap
#      name: cloudflare-proxied-networks
#      valuesKey: cloudflare-proxied-networks.txt
