---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: emqx
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: emqx
      version: 11.1.1
      sourceRef:
        kind: HelmRepository
        name: emqx
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    replicaCount: 1
    # resources:
    # requests:
    #    cpu: 100m
    #    memory: 128Mi
    #  limits:
    #    memory: 256Mi
    service:
      type: ClusterIP
    image:
      # repository: emqx/emqx
      # tag: 11-debian-11-r43
      pullPolicy: IfNotPresent
    persistence:
      enabled: true
      existingClaim: emqx-pvc
    ingress:
      ## ingress for EMQX Dashboard
      dashboard:
        enabled: true
        annotations:
          # kubernetes.io/ingress.class: nginx
          # kubernetes.io/tls-acme: "true"
          cert-manager.io/cluster-issuer: "letsencrypt-staging"
          external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
          external-dns/is-public: "true"
        path: /
        pathType: ImplementationSpecific
        hosts:
          - dashboard-emqx.${SECRET_DOMAIN}
        tls: []
