# yamllint disable
apiVersion: v1
kind: Secret
metadata:
  name: authelia-postgresql-secret
  namespace: networking
stringData:
  password: ${BOOTSTRAP_AUTHELIA_STORAGE_PASSWORD}
  # password: ${BOOTSTRAP_AUTHELIA_DB_PASSWORD}
  postgres-password: ${BOOTSTRAP_AUTHELIA_DB_ADMIN_PASSWORD}
