# yamllint disable
apiVersion: v1
kind: Secret
metadata:
  name: authelia-postgresql-secret
  namespace: kube-system
stringData:
  password: ${BOOTSTRAP_AUTHELIA_STORAGE_PASSWORD}
  postgres-password: ${BOOTSTRAP_AUTHELIA_DB_ADMIN_PASSWORD}
