---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: ${BOOTSTRAP_TIMEZONE}
  NETWORK_K8S_CLUSTER_CIDR: 10.42.0.0/16
  NETWORK_K8S_SERVICE_CIDR: 10.43.0.0/16
  # SECRET_METALLB_LB_RANGE: ${BOOTSTRAP_METALLB_LB_RANGE}
  # SECRET_METALLB_K8S_GATEWAY_ADDR: ${BOOTSTRAP_METALLB_K8S_GATEWAY_ADDR}
  # SECRET_METALLB_INGRESS_ADDR: ${BOOTSTRAP_METALLB_INGRESS_ADDR}
