---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: ${BOOTSTRAP_TIMEZONE}
  # SECRET_METALLB_LB_RANGE: ${BOOTSTRAP_METALLB_LB_RANGE}
  # SECRET_METALLB_K8S_GATEWAY_ADDR: ${BOOTSTRAP_METALLB_K8S_GATEWAY_ADDR}
  # SECRET_METALLB_INGRESS_ADDR: ${BOOTSTRAP_METALLB_INGRESS_ADDR}
