# yamllint disable
apiVersion: v1
kind: Secret
metadata:
  name: grafana-secrets
  namespace: monitoring
stringData:
  admin-user: ${BOOTSTRAP_GRAFANA_ADMIN_USER}
  admin-password: ${BOOTSTRAP_GRAFANA_ADMIN_PASSWORD}
