---
apiVersion: v1
kind: Secret
metadata:
    name: lldap
    namespace: networking
stringData:
    SECRET_LLDAP_JWT_SECRET: ${BOOTSTRAP_LLDAP_JWT_SECRET}
    SECRET_LLDAP_USER_PASS:  ${BOOTSTRAP_LLDAP_USER_PASS}
