---
apiVersion: v1
kind: Secret
metadata:
    name: lldap
    namespace: networking
stringData:
    SECRET_LLDAP_USER_DN: ${BOOTSTRAP_LLDAP_USER_DN}
    SECRET_LLDAP_USER_EMAIL: ${BOOTSTRAP_LLDAP_USER_EMAIL}
    SECRET_LLDAP_USER_PASS: ${BOOTSTRAP_LLDAP_USER_PASS}
