# yamllint disable
apiVersion: v1
kind: Secret
metadata:
  name: mailu-postgresql-secret
  namespace: kube-system
stringData:
  password: ${BOOTSTRAP_MAILU_STORAGE_PASSWORD}
  postgres-password: ${BOOTSTRAP_MAILU_DB_PASSWORD}
