# yamllint disable
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
  namespace: rabbitmq
stringData:
  rabbitmq-password: ${BOOTSTRAP_RABBITMQ_PASSWORD}
  rabbitmq-erlang-cookie: ${BOOTSTRAP_RABBITMQ_ERL_COOKIE}
