---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: openldap
  namespace: kube-system
spec:
  interval: 15m
  chart:
    spec:
      chart: openldap-stack-ha
      version: 3.0.2
      sourceRef:
        kind: HelmRepository
        name: jp-gouin
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    global:
      ldapDomain: ${SECRET_DOMAIN}
      adminPassword: ${SECRET_LDAP_ADMIN_PASSWORD}
      configPassword: ${SECRET_LDAP_CONFIG_PASSWORD}
    replicaCount: 1
    replication:
      enabled: false
    image:
      repository: osixia/openldap
      tag: 1.5.0
      pullPolicy: IfNotPresent
#   existingSecret: openldap-secret
    env:
      LDAP_ORGANISATION: ${SECRET_LDAP_ORGANISATION}
      LDAP_READONLY_USER_USERNAME: ${SECRET_LDAP_READONLY_USER_USERNAME}
      LDAP_READONLY_USER_PASSWORD: ${SECRET_LDAP_READONLY_USER_PASSWORD}
    persistence:
      enabled: true
      existingClaim: openldap-pvc
#    resources:
#      requests:
#        cpu: 100m
#        memory: 128Mi
#      limits:
#        memory: 256Mi
    ltb-passwd:
      enabled: false
    phpldapadmin:
      enabled: false
