apiVersion: v1
kind: Secret
metadata:
    name: openldap-secret
    namespace: kube-system
stringData:
    LDAP_ORGANISATION: ENC[AES256_GCM,data:cBU9D+cYojq/ynIX9kpu1b+S4Q==,iv:MnAPrTvezWDYMv/MLh+jByo4SWTdATyRjrX/Gtr+d1I=,tag:kQSwuWZnHHBpzz/qg/Zd+w==,type:str]
    LDAP_BINDDN: ENC[AES256_GCM,data:pIpyiYHrX7b2tVOUQI3UH9A7Noc3FO9dUisWFA==,iv:GiSg+AQ3OTqyEt9QDLZzkqhI8kTYFC39Xh1kmBna6iQ=,tag:sFb5bOl5ypD8J8D0QYuwxQ==,type:str]
    LDAP_ADMIN_PASSWORD: ENC[AES256_GCM,data:i+w+3YLctmE7tig3ef17QpuM0OuG/TgkW9miQGcbgHkflQISvDG4TKc4Ktw3RdHZWkCQ/qXFrodQWz5PIy17mw==,iv:FUuTxKmnC38j8dL//j/xD1B1ADBJ7+r9h9IPbIiaxjA=,tag:OmsXQAi39AyPGVm0XD7ppQ==,type:str]
    LDAP_CONFIG_PASSWORD: ENC[AES256_GCM,data:GO7lKh0K4vCe+ziJpDv3bFXB0FTZ/lIpbhrPaGit2aW3xiCMU+LOfAnx1/8hAuyceOfllfRkLpNLVjyqum+2dQ==,iv:Sj7r1HaeIeXLzbWJlI01jPResnQPX0TflBTkL5HFDy0=,tag:hlnwMY96J0jr1p0dSGoCcQ==,type:str]
    LDAP_READONLY_USER_USERNAME: ENC[AES256_GCM,data:wvNyLW8EO0s=,iv:pWR6CbxqVqjPMlQ1+AF07w15k8kh1WdI/4Vk+j8Dt6A=,tag:Ej7NxOsCkbzCdppKdyZ3kA==,type:str]
    LDAP_READONLY_USER_PASSWORD: ENC[AES256_GCM,data:MaIaHg4NNQOSHvGHaCGpkMdZ4e4KFhmwh5oGdoHE55ZOkEoI3NB/T8HiSwjADgBS6YEE1BHBD19df/lDx/cnDQ==,iv:Kv6jYOtaEVrRVfN4XgQaU8hRykxDFxK/GaLSx/WiNak=,tag:4cJB1JQ9vOp7Y/1kJneYGQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17cmuq9q08fkx2vd0crtmly4vlzwllf6lj83rwsvgg4p9rt0fxa5s0t0xtw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBacHJqZlJqZWQ3RWlWUTQv
            OU92YXFpblZYc21vVFM1S0FQTi9XWThFTG1VCjhvM3BHREpVWldzeElUTTczOVdX
            TDFiREdnMUJJRE5lcVgyVE5PeXFDRjAKLS0tIG1kL21tM0hqaXVBaEZmTEhsM2d2
            eXRnL3NBUTdWNVBoYjBDMVJScXY0UjQKDkIjDlXUln7X9qUIw17aJmEaShl0t8Rm
            suaz2xHl7MGfXOLirdTkAhvfokoYRWE8kJq9OlhXBU14qubFFHH0XQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-03T12:07:23Z"
    mac: ENC[AES256_GCM,data:mPJnWzGugBiCWsyFBsG8M9CD6rFvY30mfMvzCNqzNElA9VadQqKPkbYBEh6H9YLKAmeF2HX1HEDsLPIp+V6RGhwM8pquNwHzZeWZGmZwBNEqYdvxUtRhiO00lvx51KOzWZtzbjnnqjUhV4HwKyOoH4zsYBCP9YUNDvH+/CDa7k0=,iv:rWgSF62mNHrLGggmHKnPP88oFOQHluBxvyXAuovYD/E=,tag:MBlRLRHkNDKL6L9btfMqIQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
