---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openldap-pvc
  namespace: kube-system
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
