---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rabbitmq
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: rabbitmq
      version: 11.1.2
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    replicaCount: 1
    # resources:
    # requests:
    #    cpu: 100m
    #    memory: 128Mi
    #  limits:
    #    memory: 256Mi
    service:
      type: ClusterIP
    image:
      # registry: docker.io
      # repository: bitnami/rabbitmq
      # tag: 3.11.3-debian-11-r0
      pullPolicy: IfNotPresent
    auth:
      existingPasswordSecret: rabbitmq-secret
      existingErlangSecret: rabbitmq-secret
    plugins: "rabbitmq_management rabbitmq_peer_discovery_k8s"
    communityPlugins: ""
    extraPlugins: "rabbitmq_auth_backend_ldap"
    clustering:
      enabled: false
    ingress:
      enabled: true
      path: /
      hostname: lldap.${SECRET_DOMAIN}
      annotations:
        kubernetes.io/ingress.class: nginx
        cert-manager.io/cluster-issuer: "letsencrypt-staging"
        external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
        external-dns/is-public: "true"
    persistence:
      enabled: true
      existingClaim: rabbitmq-pvc
