# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: networking
stringData:
    api-key: ENC[AES256_GCM,data:C6wqp3dLBj8UQ7KMmM+4b53vflxG4Qm2JOHo9yExB4gIc/kfXDIfALW1f1aLOtM7hHU=,iv:oVTjCFZyYW9EWuZZIT/ggBqbxjmRsqqzVIRinbaw/ho=,tag:8t/tRC0fGJ1jwnDaK/ze8A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17cmuq9q08fkx2vd0crtmly4vlzwllf6lj83rwsvgg4p9rt0fxa5s0t0xtw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBak9GL0g1eEZPM3VXWEtT
            RWhpU2FWVXFudDBSck9PZlQwUDBsSTRlcFJnCjgvTTIzK3NPZGZ1ZmtVdERkR3VN
            TVdzbjgxT1JOVG5LYmNxZ2trMjJFZDgKLS0tIHRXSlRlM24rNEhhY1YvSXdOdnZy
            TFlCYUllaW5MRDZxa2xpSGQzVUFHeUkKWd29tmUcag6GQ+vPCBrP5QvFHzCDHgyJ
            qPMwpLYyDs0/zunKzF+lYE1ut9tD7Ltza5LhIQJMrN2JSU+ymJmykQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-11-22T19:21:42Z"
    mac: ENC[AES256_GCM,data:tGbFASI6FaTEj4pnPFFggRRofDqhKy+w69OEuOhOPoOK/y5dfrjbu5PvBZuipWpiecgPMqDjSV1YLPVjQMBpsBKAOxv21ZpwtBLM3VbVosSL1rUT3q4x54gnxS0utNdi+y94CZGaCKQybBXOseUv+qw+4i8SDx8gkMkKS6p01L4=,iv:rUvSwXS4/ZQpZ9+pMjFNwMGMfBqqeEZ39dS9Xa0WJNw=,tag:jbQs9YiNArxYgbfrMPIQ3Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
